### ISSUE TITLE
ValueError: zero length field name in format

### ISSUE THREAD

**Issue by matya** [arthepsy/ssh-audit#3]
You are using the `"{}".format()` that is not compatible with my python 2.6.9:

```
~ # ./ssh-audit.py -v ts01lin
# general
[info] banner: SSH-2.0-OpenSSH_6.6.1
Traceback (most recent call last):
  File "./ssh-audit.py", line 619, in <module>
    main()
  File "./ssh-audit.py", line 615, in main
    output(banner, header, kex)
  File "./ssh-audit.py", line 551, in output
    output_compatibility(kex)
  File "./ssh-audit.py", line 536, in output_compatibility
    comp_text.append('{} {}-{}'.format(sshd_name, v[0], v[1]))
ValueError: zero length field name in format
```

**Comment by matya** [comment]
Try this patch:

```
# diff -u ssh-audit.py.orig ssh-audit.py
--- ssh-audit.py.orig   2016-08-30 12:12:19.000000000 +0200
+++ ssh-audit.py        2016-08-30 12:12:33.000000000 +0200
@@ -31,7 +31,7 @@
 def usage():
        p = os.path.basename(sys.argv[0])
        out.head('# {0} v1.0.20160812, moo@arthepsy.eu'.format(p))
-       out.info('\nusage: {} [-nv] host[:port]\n'.format(p))
+       out.info('\nusage: {0} [-nv] host[:port]\n'.format(p))
        out.info('   -v  verbose')
        out.info('   -n  disable colors' + os.linesep)
        sys.exit(1)
@@ -169,7 +169,7 @@
                                self.__sock = socket.create_connection((host, port), cto)
                                self.__sock.settimeout(rto)
                        except Exception as e:
-                               out.fail('[fail] {}'.format(e))
+                               out.fail('[fail] {0}'.format(e))
                                sys.exit(1)

                def __enter__(self):
@@ -526,14 +526,14 @@
        comp_text = []
        for sshd_name, v in ssh_timeframe.items():
                if v[cp] is None:
-                       comp_text.append('{} {}+'.format(sshd_name, v[0]))
+                       comp_text.append('{0} {1}+'.format(sshd_name, v[0]))
                elif v[0] == v[1]:
-                       comp_text.append('{} {}'.format(sshd_name, v[0]))
+                       comp_text.append('{0} {1}'.format(sshd_name, v[0]))
                else:
                        if v[1] < v[0]:
-                               comp_text.append('{} {}+ (some functionality from {})'.format(sshd_name, v[0], v[1]))
+                               comp_text.append('{0} {1}+ (some functionality from {2})'.format(sshd_name, v[0], v[1]))
                        else:
-                               comp_text.append('{} {}-{}'.format(sshd_name, v[0], v[1]))
+                               comp_text.append('{0} {1}-{2}'.format(sshd_name, v[0], v[1]))
        if len(comp_text) > 0:
                out.good('[info] compatibility: ' + ', '.join(comp_text))

```

**Comment by arthepsy** [comment]
Great, will implement it shortly. Thanks!

P.S. Have You noticed any other incompatibility with 2.6?
